server:
    port: 8082

spring:
    application:
        name: rating-data-service
    liquibase:
        enabled: true
        change-log: classpath:/db/changelog/changelog-master.xml
    datasource:
        platform: postgres
        url: jdbc:postgresql://localhost:5432/movie_service
        username: postgres
        password: root
    jpa:
        database: POSTGRESQL
        show-sql: true
        generate-ddl: true
        hibernate:
            ddl-auto: create-drop
        properties:
            hibernate:
                jdbc:
                    lob:
                        non-contextual_creation: true
